SubredditBotWeb/Models/ErrorViewModel.cs
using System;

namespace SubredditBotWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SubredditBotWeb/Models/ReviewModel.cs
using SubredditBot.Data;
using System.Collections.Generic;

namespace SubredditBotWeb.Models
{
    public class ReviewModel
    {
        public List<Comment> Comments { get; set; }

        public List<Post> Posts { get; set; }

        public string Message { get; set; }

        public string Username { get; set; }
    }
}

SubredditBotWeb/Models/StatusModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace SubredditBotWeb.Models
{
    public class StatusModel
    {
        public string Message { get; set; }
    }
}

SubredditBotWeb/Models/TestPageModel.cs
namespace ChefKnivesBotWeb.Models
{
    public class TestPageModel
    {
        public string Message { get; set; }

        public string Username { get; set; }
    }
}

SubredditBotWeb/Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace SubredditBotWeb.Controllers
{
    [AllowAnonymous]
    public class AuthenticationController : Controller
    {
        [HttpGet("~/signin")]
        public async Task<IActionResult> SignIn()
        {
            // We're only ever going to support reddit most likely
            var providers = await GetExternalProvidersAsync(HttpContext);
            var provider = providers.Single();

            // Note: the "provider" parameter corresponds to the external
            // authentication provider choosen by the user agent.
            if (string.IsNullOrWhiteSpace(provider.Name))
            {
                return BadRequest();
            }

            if (!await IsProviderSupportedAsync(HttpContext, provider.Name))
            {
                return BadRequest();
            }

            // Instruct the middleware corresponding to the requested external identity
            // provider to redirect the user agent to its own authorization endpoint.
            // Note: the authenticationScheme parameter must match the value configured in Startup.cs
            return Challenge(new AuthenticationProperties { RedirectUri = "/" }, provider.Name);
        }

        [HttpGet("~/signout"), HttpPost("~/signout")]
        public async Task<IActionResult> SignOut()
        {
            // Instruct the cookies middleware to delete the local cookie created
            // when the user agent is redirected from the external identity provider
            // after a successful authentication flow (e.g Google or Facebook).
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme, new AuthenticationProperties { RedirectUri = "/" });

            return Redirect("/");
        }

        private static async Task<AuthenticationScheme[]> GetExternalProvidersAsync(HttpContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            var schemes = context.RequestServices.GetRequiredService<IAuthenticationSchemeProvider>();

            return (from scheme in await schemes.GetAllSchemesAsync()
                    where !string.IsNullOrEmpty(scheme.DisplayName)
                    select scheme).ToArray();
        }

        private static async Task<bool> IsProviderSupportedAsync(HttpContext context, string provider)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            return (from scheme in await GetExternalProvidersAsync(context)
                    where string.Equals(scheme.Name, provider, StringComparison.OrdinalIgnoreCase)
                    select scheme).Any();
        }
    }
}

SubredditBotWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SubredditBotWeb.Models;
using Microsoft.AspNetCore.Authorization;

namespace SubredditBotWeb.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SubredditBotWeb/Controllers/ReviewController.cs
using SubredditBotWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ChefKnivesBot.Utilities;
using System.Linq;

namespace SubredditBotWeb.Controllers
{
#if DEBUG
    [AllowAnonymous]
#else
    [Authorize(Policy = "SubredditModerator")]
#endif
    public class ReviewController : Controller
    {
        private const string urlRoot = "https://www.reddit.com";

        public ReviewController()
        {

        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(new ReviewModel());
        }

        [HttpPost]
        public IActionResult Index(ReviewModel model)
        {
            if (!string.IsNullOrEmpty(model.Username))
            {
                ReviewUser(model);
            }

            return View(model);
        }

        private void ReviewUser(ReviewModel model)
        {
            var reviewTask = MakerCommentsReviewUtility.Review(model.Username, Program.ChefKnivesService.RedditPostDatabase, Program.ChefKnivesService.RedditCommentDatabase);
            var result = reviewTask.GetAwaiter().GetResult();

            model.Message = $"Reviewed {model.Username} in {result.ReviewTime} (ms). Found {result.MakerPosts.Count()} maker posts and {result.Comments.Count() - result.SelfComments.Count()} total non-maker comments.";
            model.Comments = result.Comments.OrderByDescending(o => o.CreateDate).ToList();
            model.Comments.ForEach(c => c.Permalink = $"{urlRoot}{c.Permalink}");

            model.Posts = result.Posts.OrderByDescending(o => o.CreateDate).ToList();
            model.Posts.ForEach(p => p.Permalink = $"{urlRoot}{p.Permalink}");
        }
    }
}

SubredditBotWeb/Controllers/StatusController.cs
using SubredditBot.Lib;
using SubredditBotWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Serilog;
using ChefKnivesBot;
using System;

namespace SubredditBotWeb.Controllers
{
#if DEBUG
    [AllowAnonymous]
#else
    [Authorize(Policy = "SubredditModerator")]
#endif
    public class StatusController : Controller
    {
        private readonly IConfiguration _configuration;

        public StatusController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = new StatusModel
            {
                Message = $"Uptime: {DateTime.Now - Program.StartTime}"
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult RestartService()
        {
            Program.ChefKnivesService.Dispose();
            var chefKnivesBotInitializer = new ChefKnivesBotInitializer();
            Program.ChefKnivesService = chefKnivesBotInitializer.Start(Log.Logger, _configuration, Program.DiscordService.SendModChannelMessage, Program.DryRun);
            return RedirectToAction(nameof(Index));
        }
    }
}

SubredditBotWeb/Views/Authentication/SignIn.cshtml
@using Microsoft.AspNetCore.Authentication
@model AuthenticationScheme[]

<div class="jumbotron">
    <h1>Authentication</h1>
    <p class="lead text-left">Sign in using one of these external providers:</p>
    
    @foreach (var scheme in Model)
    {
        <form action="/signin" method="post">
            <input type="hidden" name="Provider" value="@scheme.Name" />
            <input type="hidden" name="ReturnUrl" value="@ViewBag.ReturnUrl" />

            <button class="btn btn-lg btn-success" type="submit">Connect using @scheme.DisplayName</button>
        </form>
    }
</div>

SubredditBotWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <div class="text-center">
        <p>Home</p>
    </div>

SubredditBotWeb/Views/Review/Index.cshtml
@model ReviewModel;

@{
    ViewData["Title"] = "Review Page";
}
<h1>@ViewData["Title"]</h1>

<form asp-controller="Review" asp-action="Index" method="post">
    <label>Username:</label>
    <input type="text" asp-for="Username" />
    <button class="btn btn-danger" type="submit" value="Submit">Review</button>
</form>

@if (!string.IsNullOrEmpty(Model.Message))
{
    <p>@Model.Message</p>

    <h4>Posts</h4>
    <table class="table table-striped">
        <thead>
            <tr>
                <th style="width: 10%">@Html.DisplayNameFor(model => model.Posts[0].Id)</th>
                <th style="width: 10%">@Html.DisplayNameFor(model => model.Posts[0].CreateDate)</th>
                <th style="width: 25%">@Html.DisplayNameFor(model => model.Posts[0].Permalink)</th>
                <th style="width: 45%">@Html.DisplayNameFor(model => model.Posts[0].Title)</th>
                <th style="width: 10%">@Html.DisplayNameFor(model => model.Posts[0].Flair)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Posts)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Id)</td>
                    <td>@Html.DisplayFor(modelItem => item.CreateDate)</td>
                    <td><a href="@Html.DisplayFor(modelItem => item.Permalink)">Link</a></td>
                    <td>@Html.DisplayFor(modelItem => item.Title)</td>
                    <td>@Html.DisplayFor(modelItem => item.Flair)</td>
                </tr>
            }
        </tbody>
    </table>

    <h4>Comments</h4>
    <table class="table table-striped">
        <thead>
            <tr>
                <th style="width: 10%">@Html.DisplayNameFor(model => model.Comments[0].Id)</th>
                <th style="width: 10%">@Html.DisplayNameFor(model => model.Comments[0].CreateDate)</th>
                <th style="width: 25%">@Html.DisplayNameFor(model => model.Comments[0].Permalink)</th>
                <th style="width: 50%">@Html.DisplayNameFor(model => model.Comments[0].Body)</th>
                <th style="width: 5%">@Html.DisplayNameFor(model => model.Comments[0].PostLinkId)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Comments)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Id)</td>
                    <td>@Html.DisplayFor(modelItem => item.CreateDate)</td>
                    <td><a href="@Html.DisplayFor(modelItem => item.Permalink)">Link</a></td>
                    <td>@Html.DisplayFor(modelItem => item.Body)</td>
                    <td>@Html.DisplayFor(modelItem => item.PostLinkId)</td>
                </tr>
            }
        </tbody>
    </table>
}

SubredditBotWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SubredditBotWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SubredditBotWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Status" asp-action="Index">Status</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Review" asp-action="Index">Review</a>
                        </li>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="SignIn">Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="SignOut">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SubredditBotWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SubredditBotWeb/Views/Status/Index.cshtml
@model StatusModel;

@{
    ViewData["Title"] = "Status";
}
<h1>@ViewData["Title"]</h1>

<p>@Model.Message</p>

<form asp-controller="Status" asp-action="RestartService" method="post">
    <button class="btn btn-danger" type="submit" value="Submit">Restart Bot</button>
</form>